### PR TITLE
[tail] improve error messaging

### LINKED ISSUE #1177: better error handling / messaging
There's a lot of places where tails can go wrong. We need to handle each of them gracefully and with clear instructions to users on how to correct the issues.

- [x] handle case where worker has not yet been published (should be an api error code)

- [x] handle missing cloudflared: https://github.com/cloudflare/wrangler/issues/1207#issuecomment-615338332

### PR DESCRIPTION
**Pull request by EverlastingBugstopper**
Fixes #1177

### CODE REVIEW

File: src/tail/mod.rs [hunk 1]
```diff
@@ -35,6 +38,9 @@ impl Tail {
         tunnel_port: u16,
         metrics_port: u16,
     ) -> Result<(), failure::Error> {
+        is_cloudflared_installed()?;
+        print_startup_message(&target.name, tunnel_port, metrics_port);
```
Comment (ashleymichal) [inline src/tail/mod.rs:42]: why move this here? if anything perhaps we should modify the message, but i'd prefer to minimize the amount of printing being done in these fns.

File: src/tail/mod.rs [hunk 2]
```diff
@@ -74,3 +80,28 @@ impl Tail {
...
     }
 }
+
+fn is_cloudflared_installed() -> Result<(), failure::Error> {
+    // this can be removed once we automatically install cloudflared
+    if which("cloudflared").is_err() {
+        let install_url = style("https://developers.cloudflare.com/argo-tunnel/downloads/")
+            .blue()
+            .bold();
+        failure::bail!("You must install cloudflared to use wrangler tail.\n\nInstallation instructions can be found here:\n{}", install_url);
```
Comment (ashleymichal) [inline src/tail/mod.rs:90]: oh i like this. v. nice.

File: src/tail/mod.rs (hunk 1 above)
Comment (EverlastingBugstopper) [reply src/tail/mod.rs:42]: i moved it because i wanted the cloudflared error message to appear before we printed the "starting tunnel" message, and i moved it to a function because it's messy and doesn't need to be at the top level here

Comment (ashleymichal) [reply src/tail/mod.rs:42]: hrm. i think it would be good to modify the message instead to say "starting tail session" and leave it. pulling to fn is good though. long term if we need more granular status updates we can use messaging to trigger them.

Comment (ashleymichal) [reply src/tail/mod.rs:42]: withdrawn. multitasking today and i thought this was tunnel.rs.
