### PR TITLE
fix(style): clippy lints

### LINKED ISSUE #183: dead code warning in wranglerjs
```
warning: method is never used: `new_at`
  --> src/wranglerjs/mod.rs:56:5
   |
56 |     fn new_at(out: String) -> Bundle {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default
```

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #183

### CODE REVIEW

File: src/wranglerjs/mod.rs [hunk 1]
```diff
@@ -53,8 +53,10 @@ impl Bundle {
             out: BUNDLE_OUT.to_string(),
         }
     }
+
+    #[cfg(test)]
```
Comment (xtuc) [inline src/wranglerjs/mod.rs]: Fixes #183
