### PR TITLE
Revert default installer location change and release 1.14.1

### LINKED ISSUE #1796: Unable to install wrangler
### 🐛 Bug report

I'm unable to install wrangler. Most probably reason is the binary-install stuff in 1.14

#### Describe the bug

I try to install wrangler. It fails :D

```
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@cloudflare/wrangler
npm ERR! command failed
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! internal/modules/cjs/loader.js:883
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '@cloudflare/binary-install'
npm ERR! Require stack:
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/binary.js
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:88:18)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:1:20)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js',
npm ERR!     '/usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js'
npm ERR!   ]
npm ERR! }
```
#### Reproduce the bug

`npm i -g @cloudflare/wrangler`

#### Expected behavior

It installs wrangler

#### Environment and versions

Fill out the following information about your environment.

* operating system: macOS Big Sur 11.1
* output of `wrangler -V`: 👷 ✨  wrangler 1.13.0
* output of `node -v`: v14.16.0
* content of `wrangler.toml`: N/A

### PR DESCRIPTION
**Pull request by xortive**
I had tested this using `npm pack`, but it seems that when installing using the actual npm package, this change is causing issues for folks on npm@7. Let's revert to the known-good homedir install location until we figure out what's going on.

I also included some edits to the release  checklist that involve tagging the release after the release PR is merged. This makes fix and release PRs like this one work better, and it fixes some parts of github's CI that expect release tags to be tagged on the default branch

closes #1796

### CODE REVIEW

File: npm/binary.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ const getBinary = () => {
   const customPath =
     process.env.WRANGLER_INSTALL_PATH ||
     process.env.npm_config_wrangler_install_path;
-  const installDirectory = join(customPath || __dirname, "wrangler");
+  const installDirectory = join(customPath || os.homedir(), ".wrangler");
```
Comment (xortive) [inline npm/binary.js:41]: https://github.com/cloudflare/wrangler/blob/v1.13.0/npm/binary.js#L33

**Review by xtuc — APPROVED** [review]

**Comment by Siilwyn** [comment]
Another approach could be using `optionalDependencies` like described here: https://github.com/evanw/esbuild/issues/789#issuecomment-782487545

**Comment by jasikpark** [comment]
I'm still getting an error when using `1.14.1` instead of `1.14.0` ... https://github.com/cloudflare/wrangler-action/issues/50#issuecomment-791974241
