### PR TITLE
Move TOML table fields come later than other fields

### LINKED ISSUE #2037: Serializing manifest result in TOML error
#### Describe the bug

When trying to serialize `wrangler::settings::toml::Manifest` with some non-none `HashMap` value, the TOML serializer throws [ValueAfterTable error](https://github.com/alexcrichton/toml-rs/blob/d8a9a98cbbaa3c734e972ed8809ff62a6f4a781c/src/ser.rs#L131-L134). This is because TOML requires that table fields must come after other fields. 

#### Reproduce the bug

The following code panics.

```rust
let manifest = Manifest {
    vars: Some(vec![
        (String::from("FOO"), String::from("some value")),
    ].into_iter().collect()),
    ..Default::default()
};
println!("{}", toml::to_string(&manifest).unwrap());
```

#### Expected behavior

The manifest is correctly serialized.

#### Environment and versions

* output of `wrangler -V`:
`1.19.0`

### PR DESCRIPTION
**Pull request by antiphoton**
Fixes #2037

### CODE REVIEW

File: src/settings/toml/manifest.rs [hunk 1]
```diff
@@ -714,4 +714,15 @@ mod tests {
 
         Ok(())
     }
+
+    #[test]
+    fn serialize() {
+        let manifest = Manifest {
+            vars: Some(vec![
+                (String::from("FOO"), String::from("some value")),
+            ].into_iter().collect()),
```
Comment (mrbbot) [inline src/settings/toml/manifest.rs:723]: Looks good! 🙂  Would you be able to format this with `rustfmt` so it passes the linter?
```suggestion
            vars: Some(
                vec![(String::from("FOO"), String::from("some value"))]
                    .into_iter()
                    .collect(),
            ),
```

**Review by mrbbot — CHANGES_REQUESTED** [review]

File: src/settings/toml/manifest.rs (hunk 1 above)
Comment (antiphoton) [reply src/settings/toml/manifest.rs]: Done

**Review by mrbbot — APPROVED** [review]

**Comment by antiphoton** [comment]
@mrbbot Could you re-run the GitHub actions workflows?

**Review by mrbbot — APPROVED** [review]

**Comment by threepointone** [comment]
Thanks for this PR!
