### PR TITLE
Ignore uploading node_modules

### LINKED ISSUE #667: Sourcemaps are unable to be uploaded when publishing a site with Wrangler
### 🐛 Bug Report

When trying to publish a Gatsby site, the sourcemaps generated for each page are large enough that they make the `publish` step fail. IMO we should ignore the sourcemap files (maybe via a config) or warn on this instead of throwing an error.

```
❯ ~/.cargo/bin/wrangler publish
🌀  Creating namespace for Workers Site "__frontendjobs-closedsource-workers_sites_assets"
Error: File `component---src-pages-post-js-c6d1c3aab5c008b72fa8.js.map-b3fd6703031f027b11dd2dc7e3448fe3838efa53e5c6436c4aa3dd9c721cc7e4` of 3252144 bytes exceeds the maximum value size limit of 2097152 bytes
```

#### Environment

`wrangler` built from master this AM 

#### Steps to reproduce

Run `wrangler publish` on a Workers site with large sourcemaps. Sorry, my project is closed-source, but happy to give access to Wrangler team if needed!

### PR DESCRIPTION
**Pull request by gabbifish**
This PR closes #667. It is a first overture towards one day handling #464, aka adding `.wignore` functionality.

This PR introduces logic for filtering files the bucket `upload` function traverses. Namely, it creates a base for filtering two types of items:
1. directories
1. files with certain prefixes (like dotfiles).

Directories are entirely filtered if they match a certain directory name, in this case `node_modules`. Files are filtered if their prefix matches one that is intended to be filtered.

This reduces the number of times someone is likely to hit the KV maximum size API error via node_module or Gatsby site sourcemap uploads.

### CODE REVIEW

File: src/commands/kv/bucket/upload.rs [hunk 1]
```diff
@@ -94,19 +96,31 @@ fn call_put_bulk_api(
...
         }
     }
     filtered_pairs
 }
 
+// todo(gabbi): Replace all the logic below with a proper .wignore implementation
+// when possible.
+const KNOWN_UNNECESSARY_PREFIXES: &'static [&str] = &[
+    "node_modules/", // npm vendoring
+    "component---",  // Gatsby sourcemaps
```
Comment (ashleymichal) [inline src/commands/kv/bucket/upload.rs]: are these _always_ too big? curious if we should include for a first pass.

File: src/commands/kv/bucket/upload.rs [hunk 2]
```diff
@@ -94,19 +96,31 @@ fn call_put_bulk_api(
...
+];
+fn if_ignored_prefix(key: &str) -> bool {
```
Comment (ashleymichal) [inline src/commands/kv/bucket/upload.rs]: nit:
```suggestion
fn contains_ignored_prefix(key: &str) -> bool {
```

File: src/commands/kv/bucket/upload.rs [hunk 3]
```diff
@@ -94,19 +96,31 @@ fn call_put_bulk_api(
...
+    for prefix in KNOWN_UNNECESSARY_PREFIXES {
+        if key.starts_with(prefix) {
```
Comment (ashleymichal) [inline src/commands/kv/bucket/upload.rs]: for this first pass w/ just node_modules, should we ignore any path that includes node_modules?

File: src/commands/kv/bucket/upload.rs (hunk 1 above)
Comment (gabbifish) [reply src/commands/kv/bucket/upload.rs]: they're apparently quite the menace (and unnecessary) for gatsby users--there are plenty of js libs that allow folks to skip generating them at all. I think we can get away with ignoring them completely, but I'd love @signalnerve's input before I do anything too rash :)

Comment (ashleymichal) [reply src/commands/kv/bucket/upload.rs]: yah word; if nothing else we can always do a one-liner with just that.

File: src/commands/kv/bucket/upload.rs (hunk 3 above)
Comment (gabbifish) [reply src/commands/kv/bucket/upload.rs]: Hmm, where else would node modules live? I'm not opposed to it, it just seems like unorthodox ignoring behavior (it usually follows prefixes, not the presence of a string)

Comment (ashleymichal) [reply src/commands/kv/bucket/upload.rs]: i noticed as i was developing https://github.com/cloudflare/wrangler/pull/708 that the key itself still includes the directory name, so this... might not work? or if it does i am confused as to why?

Comment (ashleymichal) [reply src/commands/kv/bucket/upload.rs]: turns out i broke this.

Comment (gabbifish) [reply src/commands/kv/bucket/upload.rs]: I added more finessed logic for looking at whether a `node_module` subdirectory existed anywhere within a bucket :) So @ashleymichal we should have your suggested functionality ready to go!

File: src/commands/kv/bucket/mod.rs [hunk 4]
```diff
@@ -26,7 +26,10 @@ pub fn directory_keys_values(
     let mut upload_vec: Vec<KeyValuePair> = Vec::new();
     let mut key_manifest: HashMap<String, String> = HashMap::new();
 
-    for entry in WalkDir::new(directory) {
+    for entry in WalkDir::new(directory)
+        .into_iter()
+        .filter_entry(|e| !is_ignored(e))
```
Comment (ashleymichal) [inline src/commands/kv/bucket/mod.rs]: ✨

**Comment by ashleygwilliams** [comment]
so i have a approach question - gatsby source maps are not always too big- i think we may just want this to block node_modules for now, and then we can explore the .wranglerignore to ignore too big files, so folks opt in

File: src/commands/kv/bucket/upload.rs (hunk 1 above)
Comment (ashleygwilliams) [reply src/commands/kv/bucket/upload.rs]: heh just realized my comment below is on this. i would say we should opt to not do it in this one and then do the .wranglerignore to address these... thoughts?

Comment (gabbifish) [reply src/commands/kv/bucket/upload.rs]: I'm happy to remove it for now!

**Comment by gabbifish** [comment]
@ashleygwilliams updated this PR to remove the gatsby sourcemap logic. Let me know if this is good to go! :D

**Comment by ashleymichal** [comment]
LGTM! ✅

File: src/commands/kv/bucket/mod.rs [hunk 5]
```diff
@@ -128,3 +160,87 @@ fn get_digest(value: String) -> Result<String, failure::Error> {
...
+
+    #[test]
+    fn it_can_ignore_prefix() {
+        let file_name = ".dotfile";
+        // If test file already exists, delete it.
+        if fs::metadata(file_name).is_ok() {
+            fs::remove_file(file_name).unwrap();
+        }
+
+        fs::File::create(file_name).unwrap();
```
Comment (EverlastingBugstopper) [inline src/commands/kv/bucket/mod.rs]: do these tests create a real file in the file system or just something in memory? would be great if we didn't add more tests relying on file system but i'm not going to block on this

Comment (gabbifish) [reply src/commands/kv/bucket/mod.rs]: I tried using tempfiles but had absolutely no success :( It seems that the tempfiles crate is NOT for testing purposes like mine (it produces temp gobbledygook directory names instead of allowing you to create a directory with the name you want, e.g. `node_modules`). So, I had to revert to using a real file in the filesystem.

Comment (EverlastingBugstopper) [reply src/commands/kv/bucket/mod.rs]: ok :)

Comment (ashleygwilliams) [reply src/commands/kv/bucket/mod.rs]: agree, but also can say this is a major RM planned for Q4

**Comment by ashleygwilliams** [comment]
WIP- @EverlastingBugstopper to refactor code to remove double asset manifest generation to remove the double error message printing.
