### PR TITLE
Have live reload preview watch over entire rust worker directory

### LINKED ISSUE #522: Live update preview doesn't work for rust projects
#### Environment

* operating system:
* output of `rustc -V`: rustc 1.36.0 (a53f9df32 2019-07-03)
* output of `node -v`: v8.10.0
* output of `wrangler -V`: wrangler 1.2.0

#### Steps to reproduce

```
wrangler generate rust-test --type=rust
cd rust-test
wrangler preview --watch
```

#### What did you expect to see?
Live reload should successfully stay alive

#### What did you see instead?
```
$ wrangler preview --watch
⬇️ Installing wasm-pack...
 Compiling your project to WebAssembly...
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.01s
[INFO]: Installing wasm-bindgen...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 0.09s
[INFO]: :-) Your wasm pkg is ready to publish at ./pkg.
⬇️ Installing wasm-pack...
Error: Your JavaScript project is missing a `package.json` file; is `./` the wrong directory?
```

### PR DESCRIPTION
**Pull request by gabbifish**
Closes #522.

This change has the live reload functionality watch over the entire rust worker directory, and does not look for package.json files that do not typically exist for rust wasm projects.

### CODE REVIEW

File: src/commands/build/watch/mod.rs [hunk 1]
```diff
@@ -2,19 +2,18 @@ mod watcher;
...
 use crate::{commands, install};
 
 use notify::{self, RecursiveMode, Watcher};
-use std::env;
 use std::sync::mpsc;
 use std::thread;
 use std::time::Duration;
 
 pub const COOLDOWN_PERIOD: Duration = Duration::from_millis(2000);
 const JAVASCRIPT_PATH: &str = "./";
```
Comment (xtuc) [inline src/commands/build/watch/mod.rs]: For JavaScript I guess we are watching `node_modules` as well.

Comment (gabbifish) [reply src/commands/build/watch/mod.rs]: Yup!

File: src/commands/build/watch/mod.rs [hunk 2]
```diff
@@ -51,19 +50,12 @@ pub fn watch_and_build(
...
                 let (watcher_tx, watcher_rx) = mpsc::channel();
                 let mut watcher = notify::watcher(watcher_tx, Duration::from_secs(1)).unwrap();
 
-                let mut path = env::current_dir().expect("current dir");
-                path.push("src");
-
-                watcher.watch(&path, RecursiveMode::Recursive).unwrap();
-                watcher.watch(&entry, RecursiveMode::Recursive).unwrap();
-                message::info(&format!("watching {:?} and {:?}", &path, &entry));
+                watcher.watch(RUST_PATH, RecursiveMode::Recursive).unwrap();
```
[the remark this answers is not in the document]
Comment (gabbifish) [reply src/commands/build/watch/mod.rs]: It looks like the notify crate doesn't allow us to ignore dotfiles :( 
https://docs.rs/notify/5.0.0-pre.1/notify
