### PR TITLE
Fix #958: Do not factor in .gitignore into workers sites upload directory traversal

### LINKED ISSUE #958: Workers Sites uploads do not include files that are in .gitignore
#### Environment

* operating system: windows 10 pro v1909 (18363.535) 

#### Steps to reproduce
Generate workers site project, set account id, api access granted using workers site template permissions. 

Static file export of Wordpress site, placed in ./public folder

Run wrangler publish 

Some css and js and font files are not uploaded (as seen by http 500 error in chrome dev tools for those resources)

I suspect this is because the files are in a deep folder structure, because when these files are moved to root public folder or 1 folder deep, wrangler does not skip them and they are successfully deployed.

#### What did you expect to see?
I expect ALL files in ./public folder to be deployed
#### What did you see instead?
Some files are skipped during wrangler publish process

### PR DESCRIPTION
**Pull request by gabbifish**
Fixes #958. This change ensures that the wrangler include/exclude logic for workers sites bucket directory traversal does NOT take into account .gitignore. A test has been added to ensure this functionality exists.

### CODE REVIEW

File: src/commands/kv/bucket/mod.rs [hunk 1]
```diff
@@ -439,6 +443,49 @@ mod tests {
...
+            .map(|entry| entry.unwrap().path().to_owned())
+            .collect();
+
+        assert!(files.contains(&test_path));
+
+        // Why drop()? Well, fs::remove_dir_all on Windows depends on the DeleteFileW syscall.
+        // This syscalldoesn't actually delete a file, but only marks it for deletion. It still
+        // can be alive when we try to delete the parent directory test_dir, causing a "directory
+        // is not empty" error. As a result, we MUST call drop() to close the gitignore file so
+        // that it is not alive when fs::remove_dir_all(test_dir) is called.
```
Comment (ashleymichal) [inline src/commands/kv/bucket/mod.rs]: 👍

File: src/commands/kv/bucket/mod.rs [hunk 2]
```diff
@@ -439,6 +443,49 @@ mod tests {
...
+
+        let files: Vec<_> = get_dir_iterator(&target, Path::new(&upload_dir))
+            .unwrap()
+            .map(|entry| entry.unwrap().path().to_owned())
+            .collect();
+
+        assert!(files.contains(&test_path));
+
+        // Why drop()? Well, fs::remove_dir_all on Windows depends on the DeleteFileW syscall.
+        // This syscalldoesn't actually delete a file, but only marks it for deletion. It still
```
Comment (gabbifish) [inline src/commands/kv/bucket/mod.rs]:
```suggestion
        // This syscall doesn't actually delete a file, but only marks it for deletion. It still
```
